spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        premium-bought: premium_bought_channel
        profile-view:
          name:
            profile_view_channel
        goal-complete:
          name: goal_complete_channel
        like_post:
          name: like_channel
        post-view:
          name: post_view_channel
        post-published:
          name: post_published_channel
        post-comment:
          name: post_comment_channel
        achievement-received:
          name: achievement_received_channel
        follower:
          name: follower_channel
        profile-appeared-in-search:
          name: profile_appeared_in_search


server:
  port: 8097

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8092
