CREATE TABLE telegram_profile(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE ,
    user_id BIGINT UNIQUE NOT NULL,
    user_name VARCHAR NOT NULL,
    telegram_id BIGINT UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT FALSE NOT NULL
)