CREATE TABLE telegram_profile(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE ,
    userId BIGINT UNIQUE NOT NULL,
    username VARCHAR NOT NULL,
    telegramId BIGINT UNIQUE NOT NULL,
    isActive BOOLEAN DEFAULT FALSE NOT NULL
)