spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
   kafka:
    port: 6032
    host: localhost
   redis:
     port: 6033
     host: localhost

services:
  s3:
    accesskey: 1111
    secretkey: 1111
    bucketname: userbucket
    endpoint: 1111
    targetwidth: 1080
    targetheight: 560
    maxfilesize: 10