CREATE TABLE hash (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    hash VARCHAR NOT NULL UNIQUE
);

CREATE TABLE url(
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
    url VARCHAR NOT NULL,
    hash VARCHAR NOT NULL UNIQUE,
    createdAt timestamptz DEFAULT current_timestamp
);