spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        calculations_channel:
          name: calculations_channel
        like_post_channel:
          name: like_channel
        user_ban_channel:
          name: user_ban_channel
      cache:
        default-ttl: 3600
        cache-settings:
          hashtag:
            name: hashtags
          users:
            name: users
          authors:
            name: authors
          posts:
            name: posts
          comments:
            name: comments
          feed:
            name: feed
        settings:
          max-hashtags-size: 1000
          max-feed-size: 500
          max-post-comments-size: 3
      lock-registry:
        post-lock-key: POST_LOCK_KEY
        release-time-duration-millis: 10000

    kafka:
      port: 9092
      host: localhost
      group-id: post_service

      topics:
        default-partition: 1
        default-replication: 1
        topic-settings:
          comment-likes:
            name: comment-likes
          post-likes:
            name: post-likes
          posts:
            name: posts
          comments:
            name: comments
          feed-heater:
            name: feed-heater
          view-count:
            name: views

  servlet:
    multipart:
      max-file-size: 5MB

  profiles:
    active: test

server:
  port: 8091

logging:
  level:
    root: info

services:
  s3:
    endpoint: http://127.0.0.1:9000/
    accessKey: user
    secretKey: password
    bucketName: corpbucket
    targetWidth: 1080
    targetHeight: 566
    maxFilesAmount: 10


post:
  publisher:
    scheduler:
      cron: "0 0/1 * 1/1 * ?" # every minute
  ad-remover:
    scheduler:
      cron: "0 0 0 * * *"  # ?????? ???? ? ???????
    threads-count: 20
    max-list-size: 100
  moderator:
    path-curse-words: "src/main/resources/curse-words.txt"
    scheduler:
      cron: "0 0 * * * ?" # every midnight
    threads-count: 20
    max-list-size: 100
  user-ban:
    scheduler:
      cron: "0 0 * * * ?"
    channel:
      name: user_ban_channel
  correcter:
    scheduler:
      cron: "0 0 0 * * *"

user-service:
  host: localhost
  port: 8090

async.settings:
  kafka:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
  feed:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100
  hashtags:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 100


spelling:
  url: https://speller.yandex.net/services/spellservice.json/checkText?text=
  threads: 4

moderation:
  cron: "0 0 0 * * *"  # ?????? ???? ? ???????
  dictionary:
    filepath: "classpath:bad-words.txt"
  threads-count: 30
  batch-size: 100

batches:
  feed-heater:
    size: 100

api:
  path: /api/v1